### ISSUE TITLE
Some API design questions

### ISSUE THREAD

**Issue by FZambia** [synw/centcom#2]
Hi, just looking through readme examples for now:

```go
cli := centcom.New("locahost", 8001, "secret_key")
cli, err := centcom.Connect(cli)
if err != nil {
    fmt.Println(err)
    return
}
defer centcom.Disconnect(cli)
```

Maybe a more natural way would be:

```go
cli := centcom.New("locahost", 8001, "secret_key")
err := cli.Connect()
if err != nil {
    fmt.Println(err)
    return
}
defer cli.Disconnect()
```

The same for `Subscribe` method - it also returns `cli` as first return value. I can miss sth though. 

Then:

```go
// listen
go func() {
    fmt.Println("Listening ...")
    for msg := range(cli.Channels) {
            if msg.Channel == "public:data" {
                    fmt.Println("PAYLOAD", msg.Payload, msg.UID)
            }
    }
}()
```

Interesting approach. Just wondering without investigating code yet - will this routine work after reconnect to Centrifugo? Actually reconnecting part is the most difficult in all Centrifugo clients - I always struggle with it.

But the most important question I came to: in our clients we distinguish between HTTP API and client libraries (`gocent` for backend, `centrifuge-go` for client facing side) - and one of the reasons for it is different security politics: HTTP client can know `secret` key because it works from app backend, while client library must ask backend for connection credentials (without knowing `secret` key). Now this wrapper uses the same constructor for everything accepting `secret` key as initialization argument. This means that this wrapper can only be used from app backend (if use Centrifugo idiomatically) so application client does not have access to `secret` key.

**Comment by synw** [comment]
I changed the client methods to return only errors: you are right it is much better.

For the `cli.Connect()` and `cli.Disconnect()` I can not make it to work. I already tried before but I get some mysterious nil pointer problems: my understanding of Go is limited, as well as my time to investigate this, so I'll leave it this way for now.

I really have no idea if this will work after reconnect.

I do understand the Centrifugo's client/server security policy. This library is made for use in backend for programs that have access to the secret key. Maybe it would be possible to provide a  client only method for initialization with a token, and no http, I am not sure about how to do things here, I don't have a user case.

The way I built this matches my needs, and I am still confused about how the people use these drivers in Go, so I just made it my way to see what happens. Providing a client only method would be more idiomatic I agree. I need some time to think about it because I am not very comfortable with driver's code neither the usage that people do. Of course any help and suggestion from experimented Go coders like you guys are welcome.

Since I work with Go I have more and more projects around Centrifugo: a bot that relay presence info to channels so that clients don't have to fetch it (I use it for [django-presence](https://github.com/synw/django-presence): I'll distribute the Go presence script independently), and a Centrifugo terminal client similar to the web admin to get quick infos about what's going on onto the server without having to use the browser client. This is the kind of programs I want to develop with this library.

**Comment by FZambia** [comment]
> I already tried before but I get some mysterious nil pointer problems

Actually this most probably a bug in `centrifuge-go`, stack trace could help to investigate

> I really have no idea if this will work after reconnect.

It's simple to check - just restart Centrifugo and see how client behaves

Actually the more I work on `centrifuge-mobile` code the more I understand that current state of `centrifuge-go` is not that perfect. So I'll work on it more. Most of Centrifugo users use browser client and some iOS and Android libraries, I am not sure we have many users that use `centrifuge-go` at moment developing client facing apps in Go is a rare thing.

**Comment by synw** [comment]
I tried again to make the connect and disconnect methods without success. The stack trace does not say anything about centrifuge-go:

```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x63e759]

goroutine 1 [running]:
github.com/synw/centcom.Cli.Disconnect(0x6d7b22, 0x9, 0x1f41, 0x6d8128, 0xa, 0xc42001c300, 0x0, 0x0, 0x0, 0xc420015590, ...)
	/home/ggg/go/src/github.com/synw/centcom/ws.go:108 +0x29
panic(0x686740, 0x81eff0)
	/home/ggg/bin/go/src/runtime/panic.go:489 +0x2cf
github.com/synw/centcom.Cli.Subscribe(0x6d7b22, 0x9, 0x1f41, 0x6d8128, 0xa, 0xc42001c300, 0x0, 0x0, 0x0, 0xc420015590, ...)
	/home/ggg/go/src/github.com/synw/centcom/ws.go:49 +0x37
main.main()
	/home/ggg/go/src/github.com/synw/centcom/examples/publish.go:29 +0x1b5
exit status 2
```
I made a branch with this code.

It does not work after reconnect, seems that there is a some work to do here.

For the future if you say that the centrifuge-go code is not optimal why not to move all to centrifuge-mobile, as it is the up to date working code? I can adapt my library to use it when ready. I should try an implementation just to check it out when I have a bit of time.
